#!/bin/sh

### BEGIN INIT INFO
# Provides:          viriatum
# Required-Start:    $local_fs $remote_fs $network $syslog
# Required-Stop:     $local_fs $remote_fs $network $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Starts the viriatum web server
# Description:       Starts the viriatum web server
### END INIT INFO

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
DAEMON=/usr/sbin/viriatum
NAME=viriatum
DESC="Viriatum web server agent"

test -x $DAEMON || DAEMON=/usr/bin/viriatum
test -x $DAEMON || DAEMON=/usr/local/bin/viriatum
test -x $DAEMON || exit 0

set -e

. /lib/lsb/init-functions

case "$1" in
    start)
        log_daemon_msg "Starting $DESC" viriatum
        start-stop-daemon --start --quiet --pidfile /var/run/$NAME.pid \
            --exec $DAEMON -- --daemon || true
        log_end_msg 0
        ;;

    stop)
        log_daemon_msg "Stopping $DESC" viriatum
        start-stop-daemon --stop --quiet --pidfile /var/run/$NAME.pid \
            --exec $DAEMON || true
        log_end_msg 0
        ;;

    restart|force-reload)
        log_daemon_msg "Restarting $DESC" viriatum
        start-stop-daemon --stop --quiet --pidfile \
            /var/run/$NAME.pid --exec $DAEMON || true
        sleep 1
        start-stop-daemon --start --quiet --pidfile \
            /var/run/$NAME.pid --exec $DAEMON -- --daemon || true
        log_end_msg 0
        ;;
    *)
        echo "Usage: $NAME {start|stop|restart|force-reload}" >&2
        exit 1
        ;;
esac

exit 0
